### ISSUE TITLE
`--no-color` option

### ISSUE THREAD

**Issue by imishinist** [itamae-kitchen/mitamae#111]
I'd like to save the log during provisioning, but the text in the color output is hard to see, so I'd like to add the `--no-color` option.
I thought about writing it myself and sending out a PR.
But I gave up because I didn't know how to develop on mruby and CONTRIBUTING.md was not found.

Can you add it?
Or can you tell me how to develop it?

**Comment by k0kubun** [comment]
> But I gave up because I didn't know how to develop on mruby and CONTRIBUTING.md was not found.

Sorry about that. I updated that part https://github.com/itamae-kitchen/mitamae/commit/13e811084a2c52098fcdf3596bd2e79d73372b60.

**Comment by imishinist** [comment]
I ran a test and got an error.

If I set SKIP_MITAMAE_COMPILE to 1, the test passes.
However, since I added the option, I think it needs to be compiled. if I set SKIP_MITAMAE_COMPILE to 0 and run it, I get the following error.

```
git --git-dir /home/mruby/code/mruby/build/repos/linux-x86_64/mruby-singleton/.git --work-tree /home/mruby/code/mruby/build/repos/linux-x86_64/mruby-singleton checkout --detach 73dd4bae1a47d82e49b8f85bf27f49ec4462052e
GIT CHECKOUT DETACH /home/mruby/code/mruby/build/repos/linux-x86_64/mruby-singleton -> 73dd4bae1a47d82e49b8f85bf27f49ec4462052e
HEAD is now at 73dd4ba Merge pull request #2 from take-cheeze/patch-1
** Invoke compile (first_time)
** Invoke all (first_time)
** Invoke gensym (first_time)
rake aborted!
Don't know how to build task '/home/mruby/code/mruby/build/host/mrbgems/mruby-onig-regexp/onigmo-6.2.0/libonig_objs/iso_8859_4.pi' (see --tasks)
/usr/lib/ruby/vendor_ruby/rake/task_manager.rb:62:in `[]'
/usr/lib/ruby/vendor_ruby/rake/file_task.rb:32:in `block in out_of_date?'
/usr/lib/ruby/vendor_ruby/rake/file_task.rb:32:in `any?'
/usr/lib/ruby/vendor_ruby/rake/file_task.rb:32:in `out_of_date?'
/usr/lib/ruby/vendor_ruby/rake/file_task.rb:16:in `needed?'
/usr/lib/ruby/vendor_ruby/rake/task.rb:221:in `format_trace_flags'
/usr/lib/ruby/vendor_ruby/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => compile => all => gensym => /home/mruby/code/mruby/build/host/presym
```

What am I doing wrong?

**Comment by k0kubun** [comment]
Sorry, it seems to be an error of mruby-onig-regexp, not mitamae's. This place is not appropriate for discussing it. Please report it to https://github.com/mattn/mruby-onig-regexp instead.
